Log:
  Level: warning # Log level: none, error, warning, info, debug 
  AccessPath: # /etc/XMPlus/access.Log
  ErrorPath: # /etc/XMPlus/error.log
DnsConfigPath:  #/etc/XMPlus/dns.json   #https://xtls.github.io/config/dns.html
RouteConfigPath: # /etc/XMPlus/route.json   #https://xtls.github.io/config/routing.html
InboundConfigPath: # /etc/XMPlus/inbound.json  #https://xtls.github.io/config/inbound.html#inboundobject
OutboundConfigPath: # /etc/XMPlus/outbound.json   #https://xtls.github.io/config/outbound.html
ConnectionConfig:
  Handshake: 8 
  ConnIdle: 300 
  UplinkOnly: 0 
  DownlinkOnly: 0 
  BufferSize: 64
Nodes:
  -
    ApiConfig:
      ApiHost: "https://www.xyz.com"
      ApiKey: "123"
      NodeID: 1
      Timeout: 30 
      RuleListPath: /etc/XMPlus/rulelist #Path to local rulelist file
    ControllerConfig:
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      DNSStrategy: AsIs # AsIs, UseIP, UseIPv4, UseIPv6
      CertConfig:
        Email: author@xmplus.dev                    # Required when Cert Mode is not none
        CertFile: /etc/XMPlus/node1.xmplus.dev.crt  # Required when Cert Mode is file
        KeyFile: /etc/XMPlus/node1.xmplus.dev.key   # Required when Cert Mode is file
        Provider: cloudflare                        # Required when Cert Mode is dns
        CertEnv:                                    # Required when Cert Mode is dns
          CLOUDFLARE_EMAIL:                         # Required when Cert Mode is dns
          CLOUDFLARE_API_KEY:                       # Required when Cert Mode is dns
      EnableFallback: false # Only support for Trojan and Vless
      FallBackConfigs:  # Support multiple fallbacks
        - SNI: # TLS SNI(Server Name Indication), Empty for any
          Alpn: # Alpn, Empty for any
          Path: # HTTP PATH, Empty for any
          Dest: 80 # Required, Destination of fallback, check https://xtls.github.io/config/features/fallback.html for details.
          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for disable        IPLimit:
      IPLimit:
        Enable: false # Enable the global ip limit of a user 
        RedisNetwork: tcp # Redis protocol, tcp or unix
        RedisAddr: 127.0.0.1:6379 # Redis server address, or unix socket path
        RedisUsername: default # Redis username
        RedisPassword: YOURPASSWORD # Redis password
        RedisDB: 0 # Redis DB
        Timeout: 5 # Timeout for redis request
        Expiry: 60 # Expiry time (second) 
#  -
#    ApiConfig:
#      ApiHost: "https://www.xyz.com"
#      ApiKey: "123"
#      NodeID: 2
#      Timeout: 30 
#      RuleListPath:  /etc/XMPlus/rulelist #Path to local rulelist file
#    ControllerConfig:
#      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
#      DNSStrategy: AsIs # AsIs, UseIP, UseIPv4, UseIPv6
#      CertConfig:
#        Email: author@xmplus.dev                    # Required when Cert Mode is not none
#        CertFile: /etc/XMPlus/node1.xmplus.dev.crt  # Required when Cert Mode is file
#        KeyFile: /etc/XMPlus/node1.xmplus.dev.key   # Required when Cert Mode is file
#        Provider: cloudflare                        # Required when Cert Mode is dns
#        CertEnv:                                    # Required when Cert Mode is dns
#          CLOUDFLARE_EMAIL:                         # Required when Cert Mode is dns
#          CLOUDFLARE_API_KEY:                       # Required when Cert Mode is dns
#      EnableFallback: false # Only support for Trojan and Vless
#      FallBackConfigs:  # Support multiple fallbacks
#        - SNI: # TLS SNI(Server Name Indication), Empty for any
#          Alpn: # Alpn, Empty for any
#          Path: # HTTP PATH, Empty for any
#          Dest: 80 # Required, Destination of fallback, check https://xtls.github.io/config/features/fallback.html for details.
#          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for disable 
#     IPLimit:
#        Enable: false # Enable the global ip limit of a user 
#        RedisNetwork: tcp # Redis protocol, tcp or unix
#        RedisAddr: 127.0.0.1:6379 # Redis server address, or unix socket path
#        RedisUsername: default # Redis username
#        RedisPassword: YOURPASSWORD # Redis password
#        RedisDB: 0 # Redis DB
#        Timeout: 5 # Timeout for redis request
#        Expiry: 60 # Expiry time (second) 